package main

func builtinTemplates() []ReportTemplate {
	return []ReportTemplate{
		// === Data Audit ===
		{
			ID:          "app-accounts-entitlements-audit",
			Name:        "App Accounts & Entitlements Audit",
			Description: "One row per user with all entitlements consolidated — the original c1-report-tool report",
			Category:    "Data Audit",
			Builtin:     true,
			DataSource:  "user_audit",
			Columns: []string{
				"displayName", "email", "username",
				"identityUserId", "orphaned", "status", "appUserType",
				"createdAt", "updatedAt",
				"grantCount", "entitlements", "grantDetails",
			},
			SortBy: "displayName",
			Format: "csv",
		},
		{
			ID:          "all-users-entitlements",
			Name:        "All Users & Entitlements",
			Description: "Complete list of all account-entitlement grants for an app",
			Category:    "Data Audit",
			Builtin:     true,
			DataSource:  "grants",
			Columns: []string{
				"appUserDisplayName", "appUserEmail", "appUserUsername",
				"appUserStatus", "appUserType",
				"entitlementDisplayName", "entitlementAlias", "entitlementResourceType",
				"grantedAt", "expiresAt",
			},
			SortBy: "appUserDisplayName",
			Format: "csv",
		},
		{
			ID:          "orphaned-accounts",
			Name:        "Orphaned Accounts",
			Description: "App users with no identity mapping in ConductorOne",
			Category:    "Data Audit",
			Builtin:     true,
			DataSource:  "app_users",
			Columns:     []string{"displayName", "email", "username", "status", "appUserType", "createdAt"},
			Filters:     []FilterValue{{ColumnID: "orphaned", Operator: "eq", Value: "Yes"}},
			SortBy:      "displayName",
			Format:      "csv",
		},
		{
			ID:          "service-accounts",
			Name:        "Service Accounts Audit",
			Description: "All service accounts and their access",
			Category:    "Data Audit",
			Builtin:     true,
			DataSource:  "app_users",
			Columns:     []string{"displayName", "email", "username", "status", "grantCount", "createdAt", "updatedAt"},
			Filters:     []FilterValue{{ColumnID: "appUserType", Operator: "eq", Value: "APP_USER_TYPE_SERVICE_ACCOUNT"}},
			SortBy:      "displayName",
			Format:      "csv",
		},
		{
			ID:          "entitlement-grants",
			Name:        "Entitlement Grants by App",
			Description: "All entitlements sorted by number of grants",
			Category:    "Data Audit",
			Builtin:     true,
			DataSource:  "entitlements",
			Columns:     []string{"displayName", "description", "alias", "appResourceTypeId", "grantCount", "createdAt"},
			SortBy:      "grantCount",
			SortDesc:    true,
			Format:      "csv",
		},
		{
			ID:          "users-without-grants",
			Name:        "Users Without Grants",
			Description: "App users that have no entitlement grants",
			Category:    "Data Audit",
			Builtin:     true,
			DataSource:  "app_users",
			Columns:     []string{"displayName", "email", "username", "status", "appUserType", "createdAt"},
			Filters:     []FilterValue{{ColumnID: "grantCount", Operator: "eq", Value: "0"}},
			SortBy:      "displayName",
			Format:      "csv",
		},
		{
			ID:          "past-grants-history",
			Name:        "Past / Revoked Grants",
			Description: "Historical access grants with granted and revoked timestamps",
			Category:    "Data Audit",
			Builtin:     true,
			DataSource:  "past_grants",
			Columns:     []string{"appUserId", "appEntitlementId", "grantedAt", "revokedAt"},
			SortBy:      "revokedAt",
			SortDesc:    true,
			Format:      "csv",
		},

		// === Governance ===
		{
			ID:          "access-request-history",
			Name:        "Access Request History",
			Description: "All access grant requests with approvals and outcomes",
			Category:    "Governance",
			Builtin:     true,
			DataSource:  "tasks",
			Columns:     []string{"numericId", "displayName", "taskType", "state", "outcome", "outcomeTime", "userId", "createdByUserId", "createdAt"},
			Filters:     []FilterValue{{ColumnID: "taskType", Operator: "eq", Value: "grant"}},
			SortBy:      "createdAt",
			SortDesc:    true,
			Format:      "csv",
		},
		{
			ID:          "access-review-results",
			Name:        "Access Review Results",
			Description: "Certification review outcomes — what was certified vs decertified",
			Category:    "Governance",
			Builtin:     true,
			DataSource:  "tasks",
			Columns:     []string{"numericId", "displayName", "outcome", "outcomeTime", "userId", "appId", "appEntitlementId", "createdAt"},
			Filters:     []FilterValue{{ColumnID: "taskType", Operator: "eq", Value: "certify"}},
			SortBy:      "createdAt",
			SortDesc:    true,
			Format:      "csv",
		},
		{
			ID:          "revocation-activity",
			Name:        "Revocation Activity",
			Description: "All access revocations with outcomes",
			Category:    "Governance",
			Builtin:     true,
			DataSource:  "tasks",
			Columns:     []string{"numericId", "displayName", "outcome", "outcomeTime", "userId", "appId", "appEntitlementId", "createdAt"},
			Filters:     []FilterValue{{ColumnID: "taskType", Operator: "eq", Value: "revoke"}},
			SortBy:      "createdAt",
			SortDesc:    true,
			Format:      "csv",
		},
		{
			ID:          "admin-audit-log",
			Name:        "Admin Audit Log",
			Description: "System log of all admin actions and platform events",
			Category:    "Governance",
			Builtin:     true,
			DataSource:  "system_log",
			Columns:     []string{"time", "type_name", "activity_name", "actor_user", "target", "severity", "message"},
			SortBy:      "time",
			SortDesc:    true,
			Format:      "csv",
		},
		{
			ID:          "grant-change-feed",
			Name:        "Grant Change Feed",
			Description: "Audit trail of all access grant additions and removals",
			Category:    "Governance",
			Builtin:     true,
			DataSource:  "grant_feed",
			Columns:     []string{"date", "eventType", "appUserId", "appEntitlementId", "ticketId"},
			SortBy:      "date",
			SortDesc:    true,
			Format:      "csv",
		},

		// === Operations ===
		{
			ID:          "app-health-overview",
			Name:        "App Health Overview",
			Description: "All apps with owner, sync status, and user count at a glance",
			Category:    "Operations",
			Builtin:     true,
			DataSource:  "app_overview",
			Columns:     []string{"displayName", "userCount", "ownerCount", "owners", "hasOwner", "syncStatus", "syncCompletedAt"},
			SortBy:      "displayName",
			Format:      "csv",
		},
		{
			ID:          "apps-without-owners",
			Name:        "Apps Without Owners",
			Description: "Applications with no assigned owner — ownership gaps",
			Category:    "Operations",
			Builtin:     true,
			DataSource:  "app_overview",
			Columns:     []string{"displayName", "userCount", "syncStatus", "syncCompletedAt", "createdAt"},
			Filters:     []FilterValue{{ColumnID: "hasOwner", Operator: "eq", Value: "No"}},
			SortBy:      "displayName",
			Format:      "csv",
		},
		{
			ID:          "apps-with-sync-errors",
			Name:        "Apps With Sync Errors",
			Description: "Applications where the connector sync has errors",
			Category:    "Operations",
			Builtin:     true,
			DataSource:  "app_overview",
			Columns:     []string{"displayName", "owners", "syncStatus", "syncCompletedAt", "syncError"},
			Filters:     []FilterValue{{ColumnID: "syncStatus", Operator: "eq", Value: "SYNC_STATUS_ERROR"}},
			SortBy:      "displayName",
			Format:      "csv",
		},
		{
			ID:          "connector-sync-status",
			Name:        "Connector Sync Status",
			Description: "Current sync status and health for app connectors",
			Category:    "Operations",
			Builtin:     true,
			DataSource:  "connectors",
			Columns:     []string{"displayName", "syncStatus", "syncStartedAt", "syncCompletedAt", "lastError"},
			Format:      "csv",
		},
		{
			ID:          "app-owner-coverage",
			Name:        "App Owner Coverage",
			Description: "Who owns each application — verify ownership is assigned",
			Category:    "Operations",
			Builtin:     true,
			DataSource:  "app_owners",
			Columns:     []string{"displayName", "email", "department", "jobTitle", "status"},
			SortBy:      "displayName",
			Format:      "csv",
		},
	}
}
